# Generated by Django 3.2.13 on 2022-06-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='full name')),
                ('created', models.DateTimeField()),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('mac_address', models.CharField(max_length=30, unique=True, verbose_name='Mac Address')),
                ('last_humidity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='humidity')),
                ('last_temperature_c', models.FloatField(blank=True, null=True, verbose_name='temperature')),
                ('uuid', models.CharField(max_length=50, verbose_name='UUID')),
            ],
            options={
                'db_table': 'sensor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_c', models.FloatField()),
                ('created', models.DateTimeField()),
                ('humidity', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'sensor_data',
                'managed': False,
            },
        ),
    ]
